export const listLocationAttempt = /* GraphQL */` 
 query listLocationAttempt{
    listLocationAttempt{
        _id
        authenticated
        user{
            _id
            name
            lastname
            email
            privilegeID{
                _id
                name
                createdAt
                updatedAt
            }
            active
            country
            token
            verifyLogin
            createdAt
            updatedAt
            canCreateHost
            allEventWithAuth
            canAccessToApp
            canAccessToWeb
            document
            typeDocument
            code
            phone
            QR
        }
        attempts
        contact{
            _id
            firstName
            lastName
            email
            phone
            nickname
            host{
                _id
                name
                lastname
                email
                active
                country
                token
                verifyLogin
                createdAt
                updatedAt
                canCreateHost
                allEventWithAuth
                canAccessToApp
                canAccessToWeb
                document
                typeDocument
                code
                phone
                QR
            }
            verified
            typeVerified
            verifiedData{
                photo
                documentA
                documentB
                birthDate
                expirationDate
                sex
                lastName
                firstName
                nationality
                documentNumber
                correctionName
                correctionLastname
                correctionNumber
            }
            verifiedDataPDF{
                photo
                documentA
                documentB
                num1
                type
                name
                expedition
                expiration
                licNum
                num2
            }
            createdAt
            updatedAt
        }
        createdAt
        updatedAt
    }
}
`;
